# Created by: Guangyuan Yang <ygy@FreeBSD.org>

PORTNAME=	Cairo
DISTVERSION=	1.5-12.2
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	ygy@FreeBSD.org
COMMENT=	A cairo bindings for R

LICENSE=	GPLv2

TEST_DEPENDS=	R-cran-png>0:graphics/R-cran-png

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
